config {
  type: "view",
  name: "pub__assert_unclassified_small",
  schema: "rd_stage",
  tags: ["test"],
  description: "Check that unclassified share is ~0."
}

WITH x AS (
  SELECT
    country_code,
    SUM(unclassified_eng) AS sum_unclassified,
    SUM(total_eng) AS sum_total,
    SAFE_DIVIDE(SUM(unclassified_eng), NULLIF(SUM(total_eng), 0)) AS unclassified_share
  FROM ${ref("rd_mart", "pub2_country_quarter_surico4")}
  GROUP BY country_code
)
SELECT *
FROM x
WHERE unclassified_share > 1e-6
